- id: doi:10.1038/s41587-020-0645-6
  type: paper
  description: Original report of mtscATAC-seq
  date: 2020-8-12
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: source
      text: Manuscript source code
      link: https://github.com/caleblareau/mtscATACpaper_reproducibility
    - type: website
      link: https://www.10xgenomics.com/blog/introducing-the-innovator-series-hacking-atac-seq-to-perform-clonal-lineage-tracing-in-tumors
  repo: caleblareau/mtscATACpaper_reproducibility

- id: doi:10.1038/s41467-020-14667-5
  image:

- id: doi:10.1182/blood.2021013753
  image: 
  
- id: doi:10.1158/0008-5472.CAN-22-0275
  image: 
