
# highlighted articles

#Cancer cell review
- id: doi:10.1016/j.ccell.2021.11.005
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/ccellreview.png
  buttons:
    - type: paper
      text: PDF
      link: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/pdfs/Lareau-CancerCell-2021.pdf
  tags:
    - immunotherapy
    - single-cell genomics

# ASAP/DOGMA-seq paper
- id: doi:10.1038/s41587-021-00927-2
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/asapclean.png
  buttons:
    - type: paper
      text: PDF
      link: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/pdfs/MimitouLareauChen-NBT-2021.pdf
    - type: github
      text: Code
      link: https://github.com/caleblareau/asap_reproducibility
  tags:
    - immunology
    - technology development
    - single-cell genomics

#mtscatac
- id: doi:10.1038/s41587-020-0645-6
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/mtscatac.png
  buttons:
    - type: paper
      text: PDF
      link: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/pdfs/LareauLudwig-NBT-2021.pdf
    - type: github
      text: Code
      link: https://github.com/caleblareau/mtscATACpaper_reproducibility
    - type: website
      text: Coverage from 10x Genomics
      link: https://www.10xgenomics.com/blog/introducing-the-innovator-series-hacking-atac-seq-to-perform-clonal-lineage-tracing-in-tumors
  tags:
    - immunology
    - technology development
    - single-cell genomics  

# OG mito tracing paper
- id: doi:10.1016/j.cell.2019.01.022
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/mitotracing1.png
  buttons:
    - type: paper
      text: PDF
      link: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/pdfs/LudwigLareauUlirsch-Cell-2019.pdf
    - type: github
      text: Code
      link: https://github.com/caleblareau/mgatk
  tags:
    - immunology
    - technology development
    - single-cell genomics 


# Current biorxiv

#M7076
- id: doi:10.1101/2023.04.23.537997
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/m7076.png
  buttons:
    - type: github
      text: Code
      link: https://github.com/caleblareau/m7076
# HHV6
- id: doi:10.1101/2022.08.12.503683
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/hhv6sc.png

# Pearson
- id: doi:10.1101/2022.11.20.517242
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/pearson-selection.png

# Kamir
- id: doi:10.1101/2021.09.26.461821
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/kamirdc.png

# NIH cell press sneak peek
- id: doi:10.2139/ssrn.4271102
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/



############

# everything else
- id: doi:10.1038/s41467-020-14667-5
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/barcodemultiplets.png
  tags:
    - compuational method
    - single-cell genomics

- id: doi:10.1182/blood.2021013753
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/gata1307.png
  
- id: doi:10.1158/0008-5472.CAN-22-0275
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/mousemtscatac.png

- id: doi:10.1007/978-1-0716-2899-7_13
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/asapschematic.png
  
- id: doi:10.1007/978-1-0716-2899-7_14
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/mmbmtscatac.png

- id: doi:10.1038/s41596-022-00795-3
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/nprotocols.png
  
- id: doi:10.1126/sciimmunol.abl5053
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/etac-jc.png

- id: doi:10.1038/s41564-020-00846-z
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/sarscov2net.png

- id: doi:10.1056/NEJMoa2001265
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/nejmmelas.png

- id: doi:10.1016/j.cell.2020.08.008
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/bcxgcv.png

- id: doi:10.1038/s41587-019-0147-6
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/barcodetn5.png

- id: doi:10.1182/bloodadvances.2019001196
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/mitolong.png

- id: doi:10.1038/s41588-019-0362-6
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/singlecellbloodtraits.png

- id: doi:10.1002/ajh.25421
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/hbf-gencor.png

- id: doi:10.1016/j.celrep.2019.05.046
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/erydiff.png

- id: doi:10.1038/nmeth.4541
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/mousecrisprnatmeth.png

- id: doi:10.1038/nmeth.4583
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/hichippercuts.png

- id: doi:10.1038/gene.2017.3
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/sarcoidprs.png
  tags:
    - human genetics
    - autoimmunity

- id: doi:10.1093/bioinformatics/btx623
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/diffloop.png
  tags:
    - computational method

- id: doi:10.1038/gene.2016.15
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/iqtl.png
  tags:
    - computational method
    - autoimmunity

- id: doi:10.3389/fgene.2015.00312
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/dcvar.png

- id: doi:10.1002/acn3.229
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/neurosarcoidznf.png

- id: doi:10.1186/s13040-015-0040-x
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/ernetwork.png


- id: doi:10.3389/fimmu.2022.1062415
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/fimmunoeditorial.png
  tags:
    - review
    - immunology

- id: doi:10.1038/s41590-020-0796-0
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/batf3.png

- id: doi:10.1007/978-1-4939-9057-3_13
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/mmbsc.png

- id: doi:10.1007/978-1-4939-2155-3_15
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/mmbnetworks.png

- id: doi:10.1038/s41586-023-05778-2
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/linkcar.png

- id: doi:10.1038/s41590-022-01273-4
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/runx3.png

- id: doi:10.1038/s41590-022-01327-7
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/adaptnk.png

- id: doi:10.1038/s41587-022-01210-8
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/maester.png

- id: doi:10.1016/j.medj.2021.12.003
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/aastat.png
  tags:
    - human genetics
    - immunology
    - single-cell multi-omics

- id: doi:10.1038/s41591-022-01986-x
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/nmedtcell.png
  tags:
    - review
    - immunology

- id: doi:10.1016/j.xgen.2022.100166
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/figr.png
  tags:
    - computational method
    - immunology
    - single-cell multi-omics

- id: doi:10.1038/s41586-022-05089-y
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1158/2159-8290.CD-21-1491
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41586-021-04217-4
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41467-021-27666-x
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41592-021-01282-5
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41587-021-01065-5
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1126/sciimmunol.abh3768
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1158/2159-8290.CD-21-0276
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1016/j.immuni.2021.04.005
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1016/j.ccell.2021.05.007
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1016/j.cell.2020.09.056
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41586-020-2786-7
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1016/j.cell.2020.06.045
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1016/j.cell.2020.07.030
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.3389/fimmu.2020.567342
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41587-020-0535-y
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1016/j.ccell.2020.06.006
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41588-019-0568-7
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41467-020-15022-4
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41590-020-0687-4
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/immgen15.png

- id: doi:10.1016/j.cell.2018.12.036
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41586-019-1161-z
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1186/s13059-019-1854-5
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41467-019-09670-4
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41587-019-0236-6
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41588-019-0538-0
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.7554/eLife.44080
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41588-019-0363-5
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1084/jem.20181625
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1016/j.cell.2018.03.074
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41467-018-05328-9
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41588-018-0081-4
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/s41556-018-0221-1
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1038/S41591-018-0008-8
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1182/blood-2017-05-783191
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1371/journal.pbio.2002690
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1016/j.celrep.2017.09.066
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1084/jem.20170976
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1371/journal.pone.0158016
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/

- id: doi:10.1002/gepi.21739
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/encore.png
