
# highlighted articles
- id: doi:10.1038/s41587-020-0645-6
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/mtscatac.png
  buttons:
    - type: manuscript
      text: PDF
      link: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/pdfs/s41587-020-0645-6.pdf
    - type: source
      text: Source code
      link: https://github.com/caleblareau/mtscATACpaper_reproducibility
    - type: website
      text: Coverage from 10x Genomics
      link: https://www.10xgenomics.com/blog/introducing-the-innovator-series-hacking-atac-seq-to-perform-clonal-lineage-tracing-in-tumors

# everything else

- id: doi:10.1002/gepi.21739
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/encore.png

- id: doi:10.1101/2023.04.23.537997
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/m7076.png

- id: doi:10.1038/s41467-020-14667-5
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/barcodemultiplets.png

- id: doi:10.1182/blood.2021013753
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/gata1307.png
  
- id: doi:10.1158/0008-5472.CAN-22-0275
  image: https://raw.githubusercontent.com/clareaulab/clareau-lab-website/main/images/researchpngs/mousemtscatac.png

- id: doi:10.1007/978-1-0716-2899-7_13
  image: 
  
- id: doi:10.1007/978-1-0716-2899-7_14
  image: 
